# Generated by Django 5.1.1 on 2024-09-26 11:22

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=100)),
                ('new_des', tinymce.models.HTMLField()),
                ('new_slug', autoslug.fields.AutoSlugField(default=True, editable=False, null=True, populate_from='Service_title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_icon', models.CharField(max_length=50)),
                ('Service_title', models.CharField(max_length=50)),
                ('Service_des', models.TextField()),
            ],
        ),
    ]
