# Generated by Django 5.1.1 on 2024-09-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='new_slug',
        ),
    ]
