# Generated by Django 5.1.1 on 2024-09-26 12:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_remove_new_new_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=True, editable=False, null=True, populate_from='Service_title', unique=True),
        ),
    ]
